import asyncio
import json

from openai import AsyncOpenAI

import scripts.llama_chat as rag
from app.core.config import settings
from app.schemas.relevance_eval import RelevanceEvaluation


client = AsyncOpenAI(
    api_key=settings.GROQ_API_KEY,
    base_url="https://api.groq.com/openai/v1"
)

MODEL = "openai/gpt-oss-120b"

with open(
    "data/evaluation/rag_eval.json",
    "r",
    encoding="utf-8"
) as f:
    evaluation_data = json.load(f)


async def evaluate_relevance(question: str, answer: str) -> RelevanceEvaluation:
    prompt = f"""
You are evaluating the relevance of an answer
generated by a Retrieval-Augmented Generation (RAG)
system.

Your task is to determine whether the answer directly
addresses the user's question.

IMPORTANT RULES:

1. Focus only on whether the answer addresses the question.
2. Do not evaluate whether the answer is factually correct.
3. Do not use outside knowledge.
4. An answer can be relevant even if it is incomplete.
5. An answer is not relevant if it mainly discusses a different topic.
6. Return ONLY a JSON object.
7. Do not provide explanations outside the JSON object.

Question:
{question}

Answer:
{answer}

Your response MUST have exactly these fields:

{{
    "relevant": true,
    "reason": "The answer directly addresses the question."
}}
"""

    response = await client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    content = response.choices[0].message.content.strip()

    print("\nRAW RELEVANCE JUDGE RESPONSE:")
    print(content)

    start = content.find("{")
    end = content.rfind("}")

    if start == -1 or end == -1:
        raise ValueError(
            "Judge did not return a JSON object.\n"
            f"Raw response:\n{content}"
        )

    json_content = content[start:end + 1]

    data = json.loads(json_content)

    return RelevanceEvaluation.model_validate(data)

async def main():
    
    relevant_scores = []

    for index, item in enumerate(evaluation_data, start=1):
        question = item["question"]

        rag.conversation.clear()

        result = await rag.run_rag(question)

        evaluation = await evaluate_relevance(question=question, answer=result["answer"])

        relevant = evaluation.relevant
        relevant_scores.append(relevant)

        print("\n" + "=" * 70)
        print(f"Evaluation #{index}")
        print("=" * 70)

        print("\nQuestion:")
        print(question)

        print("\nGenerated Answer:")
        print(result["answer"])

        print("\nRelevant:")
        print(relevant)

        print("\nReason:")
        print(evaluation.reason)
    
    relevance_score = (sum(relevant_scores) / len(relevant_scores))
    print("\n")
    print("=" * 70)
    print("FINAL ANSWER RELEVANCE EVALUATION")
    print("=" * 70)

    print(f"Questions:       {len(relevant_scores)}")
    print(
        f"Relevance:       "
        f"{relevance_score:.3f}"
    )

if __name__ == "__main__":
    asyncio.run(main())
    